name: ci-alerts
description: a workspace alerts for CI failures

runs:
  using: 'composite'
  steps:
  - uses: actions/setup-go@v2
    with:
      go-version: '1.20'
  - run: cd ${{ github.action_path }} && go mod tidy && go run main.go
    shell: bash